---
title: "Project"
output: html_document
date: "2025-07-30"
---
#Load Packages
library(readxl)
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)

#Open Datasets
load("~/Downloads/covariate_df.rData")
library(readr)
questionnaire <- read_csv("~/Downloads/questionnaire.csv")

#Merge Datasets
cov <- covariate_df
ques <- questionnaire
merged_data <- left_join(cov, ques, by=c('SEQN'))
view(merged_data)

#Select Variables of Interest
df <- merged_data |>
  select(SEQN, RIAGENDR,RIDAGEYR, RIDRETH3, MCQ220, DMDEDUC3, SIALANG) 
  View(df)
  
#Select Complete Cases
df_comp <- df |>
  filter(!is.na(SEQN) & !is.na(RIAGENDR) & !is.na(RIDAGEYR) & !is.na(DMDEDUC3))
  View(df_comp)

#Rename Columns
df1 <- rename (df, id="SEQN", Age="RIDAGEYR", Gender="RIAGENDR", Cancer="MCQ220", Education="DMDEDUC3", Language="SIALANG", Race="RIDRETH3")
  glimpse
View(df1)

#Remove Missing Values
df_comp <- df1 |>
  filter(!is.na(Cancer))
  View(df_comp)
  
#Rename Cancer
df_comp2 <- df_comp
df_comp2$Cancer <- factor(df_comp2$Cancer, levels = c(1,2), labels = c ("Cancer", "No Cancer"), ordered = T)

#Prepare for Table 1
render.categorical <- function(x, ...) {
  c("", sapply(stats.apply.rounding(stats.default(x)), function(y) with(y,
                  sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=","), PCT))))}

my.render.cont <- function(x) {
  with(stats.apply.rounding(stats.default(x, ), digits = 3),
       c("Age_years",
         "Median [IQR]" =
           sprintf(paste("%s [%s, %s]"), MEDIAN,Q1,Q3))) }

render.strat <- function (label, n, ...) {
  sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>", 
          label, prettyNum(n, big.mark=",")) }
          
#Change Variables to Factor          
d$Gender <- factor(d$Gender, labels = c("Male", "Female"))
d$Race_Ethnicity <- factor(d$Race_Ethnicity)  # Add labels if needed
d$Education_Level <- factor(d$Education_Level)  # Add labels if needed
d$Marital_Status <- factor(d$Marital_Status)
d$Household_Size <- factor(d$Household_Size)


#Render Continuous Variables vs Categorical
my_render <- function(x, name, ...) {
  # Use mean ± SD for Age only
  if (name == "Age_years") {
    with(stats.apply.rounding(stats.default(x), digits = 1),
         sprintf("%s ± %s", MEAN, SD))
  } else {
    # Default: counts and percentages
    render.default(x, name, ...)
  }
}

library(Hmisc)
label(d$Age_years) <- "Age (years)"
label(d$Gender) <- "Gender"
label(d$Race_Ethnicity) <- "Race/Ethnicity"
label(d$Education_Level) <- "Education Level"
label(d$Marital_Status) <- "Marital Status"
label(d$Household_Size) <- "Household Size"
label(d$Income_to_Poverty_Ratio) <- "Income to Poverty"


#Table 1 Summary Table by Cancer
table1(~ Age_years  + Gender  + Race_Ethnicity + Education_Level + Marital_Status + Household_Size + Income_to_Poverty_Ratio | MCQ220, data = d, overall = "Total", caption = "Table 1: Demographic Characteristics by Cancer Status", render.var = my_render)

#Plot of Cancer Status
ggplot(d, aes(x=as.factor(MCQ220), fill=as.factor(MCQ220) )) +
labs(
x = "Cancer Status",
y = "Count",
title = "Cancer Status"
)+
  geom_bar( ) +
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5) +
  scale_fill_manual(
    values = c("No" = "#FFA500", "Yes" = "#FFDB58"),  
    labels = c("Yes" = "Cancer", "No" = "No Cancer")
  ) +
  scale_x_discrete(
  labels = c("Yes" = "Cancer", "No" = "No Cancer")
)+
  theme(plot.title = element_text(hjust = 0.5), legend.position="none", panel.background = element_rect(fill = "white"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank())
  


#Histogram of Cancer vs No Cancer Groups
library(ggplot2)
ggplot(df_comp, aes(x = factor(Cancer), y = Age, fill = factor(Cancer))) +
  geom_col(width = 0.6, alpha = 0.8) +  
  labs(
    x = "Cancer Status",  # X axis label
    y = "Age",  # Y axis label
    title = "Age by Cancer Status",  # Title
    fill = "Cancer Status"  # Legend title
  ) +
  scale_fill_manual(
    values = c("1" = "#FF69B4", "2" = "#1E90FF"),  # Custom colors for bar graph
    labels = c("1" = "Cancer", "2" = "No Cancer")  # Full labels for the legend
  ) +
  theme_minimal(base_size = 10) +  
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "#333333"),  
    axis.title.x = element_text(size = 12, face = "bold", color = "#333333"),  # Styled x axis title
    axis.title.y = element_text(size = 12, face = "bold", color = "#333333"),  # Styled y axis title
    axis.text = element_text(size = 10, color = "#333333"),  # Styled axis text
    legend.position = "bottom",  # Move legend 
    legend.title = element_text(size = 10, face = "bold"),  # Styled legend title
    legend.text = element_text(size = 10),  # Styled legend text
    panel.grid.major = element_line(color = "#DDDDDD"),  # Softer grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    panel.background = element_rect(fill = "white", color = NA),  # Panel background
    plot.background = element_rect(fill = "white", color = NA)  # Plot background
  ) +
  geom_text(
    aes(label = Age),  # Add labels showing the number of events
    vjust = -0.5,  # Position labels above the bars
    size = 3,  # Text size
    color = "#333333",  # Text color
    fontface = "bold"  # Bold font
  )
  
#Violin Plot of Age by Cancer Status
ggplot(d, aes(x = as.factor(MCQ220), y = Age_years, fill = as.factor(MCQ220))) +
  geom_violin(trim = FALSE) +
  labs(
    x = "Cancer Status",
    y = "Age",
    title = "Age Distribution by Cancer Status",
    fill = "Cancer Status"
  ) +
  scale_fill_manual(
    values = c("No" = "#FFA500", "Yes" = "#FFDB58"),
    labels = c("Yes" = "Cancer", "No" = "No Cancer")
  ) +
  scale_x_discrete(
    labels = c("Yes" = "Cancer", "No" = "No Cancer")
  ) +
  theme_minimal()
  

  
#Density of Age by Cancer Status
ggplot(d, aes(x = Age_years, fill = as.factor(MCQ220))) +
  geom_density(alpha = 0.5) +
  labs(
    x = "Age",
    y = "Age Density",
    title = "Density of Age by Cancer Status",
    fill = "Cancer Status"
  ) +
  scale_fill_manual(
    values = c("Yes" = "#FFDB58", "No" = "#FFA500"),
    labels = c("Yes" = "Cancer", "No" = "No Cancer")
  ) +
  theme_minimal()
  
#Density of Gender by Cancer Status
ggplot(d, aes(x = as.factor(MCQ220), fill = as.factor(Gender))) +
  geom_bar(position = "fill") +  
  labs(x = "Cancer Status", y = "Proportion", title="Gender Distribution by Cancer Status", fill = "Gender")+
  scale_x_discrete(
  labels = c("Yes" = "Cancer", "No" = "No Cancer")
  )+
  scale_fill_manual(
  values = c("1" = "#FFA500", "2" = "#FFDB58"),
  labels = c("1" = "Male", "2" = "Female")
)+
  theme_minimal()

#Boxplot by Age, Gender, and Cancer Status
ggplot(d, aes(x = as.factor(MCQ220), y = Age_years, fill = as.factor(Gender))) +
  geom_boxplot() +
  labs(
    x = "Cancer Status",
    y = "Age",
    fill = "Gender",
    title = "Age by Gender and Cancer Status"
  ) +
  scale_x_discrete(
    labels = c("Yes" = "Cancer", "No" = "No Cancer")
  ) +
  scale_fill_manual(
    values = c("Male" = "#FFA500", "Female" = "#FFDB58"),
    labels = c("Male" = "Male", "Female" = "Female")
  )+
  theme(plot.title = element_text(hjust = 0.5), legend.position="none", panel.background = element_rect(fill = "white"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank())